################################################################
# These are the constraints for the ZC702 evaluation board with
# two Ethernet FMCs - one connected to each FMC connector
################################################################

# Constraints for first Ethernet FMC plugged onto the LPC2 connector
# Ports are numbered 0 to 3

set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_1_rd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_0_io]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_1_rd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ref_clk_0_fsel[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_1_io]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_3_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_3_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_3_rd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_3_rd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_1_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_1_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_0_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports reset_port_0]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_1_rd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_1_rd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ref_clk_0_oe[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_1_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_2_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_2_rd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_2_rd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_3_rd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_3_rd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_0_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_0_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_0_rd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_0_rd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_0_td[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_0_td[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_1_td[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_1_td[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_1_td[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_2_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_2_rd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_2_td[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_2_td[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_2_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_2_io]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_3_td[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_3_td[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_3_td[3]}]
set_property IOSTANDARD LVDS_25 [get_ports ref_clk_0_p]
set_property IOSTANDARD LVDS_25 [get_ports ref_clk_0_n]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_0_rd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_0_rd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_0_td[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_0_txc]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_0_td[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_0_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_1_td[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_1_txc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_1_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports reset_port_1]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_2_rd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_2_td[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_2_txc]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_2_td[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_2_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports reset_port_2]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_3_td[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_3_txc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_3_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_3_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_3_io]
set_property IOSTANDARD LVCMOS25 [get_ports reset_port_3]

set_property PACKAGE_PIN U17 [get_ports {rgmii_port_1_rd[0]}]
set_property PACKAGE_PIN V17 [get_ports mdio_io_port_0_io]
set_property PACKAGE_PIN Y21 [get_ports {rgmii_port_1_rd[2]}]
set_property PACKAGE_PIN T22 [get_ports {ref_clk_0_fsel[0]}]
set_property PACKAGE_PIN U22 [get_ports mdio_io_port_1_io]
set_property PACKAGE_PIN AA9 [get_ports rgmii_port_3_rxc]
set_property PACKAGE_PIN AA8 [get_ports rgmii_port_3_rx_ctl]
set_property PACKAGE_PIN AB2 [get_ports {rgmii_port_3_rd[1]}]
set_property PACKAGE_PIN AB1 [get_ports {rgmii_port_3_rd[3]}]
set_property PACKAGE_PIN W16 [get_ports rgmii_port_1_rxc]
set_property PACKAGE_PIN Y16 [get_ports rgmii_port_1_rx_ctl]
set_property PACKAGE_PIN AB19 [get_ports mdio_io_port_0_mdc]
set_property PACKAGE_PIN AB20 [get_ports reset_port_0]
set_property PACKAGE_PIN U15 [get_ports {rgmii_port_1_rd[1]}]
set_property PACKAGE_PIN U16 [get_ports {rgmii_port_1_rd[3]}]
set_property PACKAGE_PIN V22 [get_ports {ref_clk_0_oe[0]}]
set_property PACKAGE_PIN W22 [get_ports mdio_io_port_1_mdc]
set_property PACKAGE_PIN AA7 [get_ports rgmii_port_2_rxc]
set_property PACKAGE_PIN V12 [get_ports {rgmii_port_2_rd[2]}]
set_property PACKAGE_PIN W12 [get_ports {rgmii_port_2_rd[3]}]
set_property PACKAGE_PIN U12 [get_ports {rgmii_port_3_rd[0]}]
set_property PACKAGE_PIN U11 [get_ports {rgmii_port_3_rd[2]}]
set_property PACKAGE_PIN Y19 [get_ports rgmii_port_0_rxc]
set_property PACKAGE_PIN AA19 [get_ports rgmii_port_0_rx_ctl]
set_property PACKAGE_PIN AA16 [get_ports {rgmii_port_0_rd[2]}]
set_property PACKAGE_PIN AB16 [get_ports {rgmii_port_0_rd[3]}]
set_property PACKAGE_PIN AA17 [get_ports {rgmii_port_0_td[1]}]
set_property PACKAGE_PIN AB17 [get_ports {rgmii_port_0_td[2]}]
set_property PACKAGE_PIN Y15 [get_ports {rgmii_port_1_td[0]}]
set_property PACKAGE_PIN AB14 [get_ports {rgmii_port_1_td[2]}]
set_property PACKAGE_PIN AB15 [get_ports {rgmii_port_1_td[3]}]
set_property PACKAGE_PIN T4 [get_ports rgmii_port_2_rx_ctl]
set_property PACKAGE_PIN U4 [get_ports {rgmii_port_2_rd[0]}]
set_property PACKAGE_PIN U10 [get_ports {rgmii_port_2_td[1]}]
set_property PACKAGE_PIN U9 [get_ports {rgmii_port_2_td[2]}]
set_property PACKAGE_PIN AA12 [get_ports rgmii_port_2_tx_ctl]
set_property PACKAGE_PIN AB12 [get_ports mdio_io_port_2_io]
set_property PACKAGE_PIN AB11 [get_ports {rgmii_port_3_td[0]}]
set_property PACKAGE_PIN AB10 [get_ports {rgmii_port_3_td[2]}]
set_property PACKAGE_PIN AB9 [get_ports {rgmii_port_3_td[3]}]
set_property PACKAGE_PIN Y18 [get_ports ref_clk_0_p]
set_property PACKAGE_PIN AA18 [get_ports ref_clk_0_n]
set_property PACKAGE_PIN V14 [get_ports {rgmii_port_0_rd[0]}]
set_property PACKAGE_PIN V15 [get_ports {rgmii_port_0_rd[1]}]
set_property PACKAGE_PIN V13 [get_ports {rgmii_port_0_td[0]}]
set_property PACKAGE_PIN W13 [get_ports rgmii_port_0_txc]
set_property PACKAGE_PIN T21 [get_ports {rgmii_port_0_td[3]}]
set_property PACKAGE_PIN U21 [get_ports rgmii_port_0_tx_ctl]
set_property PACKAGE_PIN Y14 [get_ports {rgmii_port_1_td[1]}]
set_property PACKAGE_PIN AA14 [get_ports rgmii_port_1_txc]
set_property PACKAGE_PIN Y13 [get_ports rgmii_port_1_tx_ctl]
set_property PACKAGE_PIN AA13 [get_ports reset_port_1]
set_property PACKAGE_PIN R6 [get_ports {rgmii_port_2_rd[1]}]
set_property PACKAGE_PIN T6 [get_ports {rgmii_port_2_td[0]}]
set_property PACKAGE_PIN V5 [get_ports rgmii_port_2_txc]
set_property PACKAGE_PIN V4 [get_ports {rgmii_port_2_td[3]}]
set_property PACKAGE_PIN U6 [get_ports mdio_io_port_2_mdc]
set_property PACKAGE_PIN U5 [get_ports reset_port_2]
set_property PACKAGE_PIN AB5 [get_ports {rgmii_port_3_td[1]}]
set_property PACKAGE_PIN AB4 [get_ports rgmii_port_3_txc]
set_property PACKAGE_PIN AB7 [get_ports rgmii_port_3_tx_ctl]
set_property PACKAGE_PIN AB6 [get_ports mdio_io_port_3_mdc]
set_property PACKAGE_PIN Y4 [get_ports mdio_io_port_3_io]
set_property PACKAGE_PIN AA4 [get_ports reset_port_3]

create_clock -period 8.000 -name ref_clk_0_p -waveform {0.000 4.000} [get_ports ref_clk_0_p]

# Constraints for second Ethernet FMC plugged onto the LPC1 connector
# Ports are numbered 4 to 7

set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_5_rd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_4_io]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_5_rd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ref_clk_1_fsel[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_5_io]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_7_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_7_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_7_rd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_7_rd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_5_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_5_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_4_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports reset_port_4]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_5_rd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_5_rd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ref_clk_1_oe[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_5_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_6_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_6_rd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_6_rd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_7_rd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_7_rd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_4_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_4_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_4_rd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_4_rd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_4_td[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_4_td[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_5_td[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_5_td[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_5_td[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_6_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_6_rd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_6_td[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_6_td[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_6_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_6_io]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_7_td[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_7_td[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_7_td[3]}]
set_property IOSTANDARD LVDS_25 [get_ports ref_clk_1_p]
set_property IOSTANDARD LVDS_25 [get_ports ref_clk_1_n]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_4_rd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_4_rd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_4_td[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_4_txc]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_4_td[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_4_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_5_td[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_5_txc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_5_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports reset_port_5]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_6_rd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_6_td[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_6_txc]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_6_td[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_6_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports reset_port_6]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_7_td[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_7_txc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_7_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_7_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_7_io]
set_property IOSTANDARD LVCMOS25 [get_ports reset_port_7]

set_property PACKAGE_PIN J18 [get_ports {rgmii_port_5_rd[0]}]
set_property PACKAGE_PIN K18 [get_ports mdio_io_port_4_io]
set_property PACKAGE_PIN M17 [get_ports {rgmii_port_5_rd[2]}]
set_property PACKAGE_PIN J16 [get_ports {ref_clk_1_fsel[0]}]
set_property PACKAGE_PIN J17 [get_ports mdio_io_port_5_io]
set_property PACKAGE_PIN D20 [get_ports rgmii_port_7_rxc]
set_property PACKAGE_PIN C20 [get_ports rgmii_port_7_rx_ctl]
set_property PACKAGE_PIN C17 [get_ports {rgmii_port_7_rd[1]}]
set_property PACKAGE_PIN C18 [get_ports {rgmii_port_7_rd[3]}]
set_property PACKAGE_PIN N19 [get_ports rgmii_port_5_rxc]
set_property PACKAGE_PIN N20 [get_ports rgmii_port_5_rx_ctl]
set_property PACKAGE_PIN N17 [get_ports mdio_io_port_4_mdc]
set_property PACKAGE_PIN N18 [get_ports reset_port_4]
set_property PACKAGE_PIN M15 [get_ports {rgmii_port_5_rd[1]}]
set_property PACKAGE_PIN M16 [get_ports {rgmii_port_5_rd[3]}]
set_property PACKAGE_PIN P16 [get_ports {ref_clk_1_oe[0]}]
set_property PACKAGE_PIN R16 [get_ports mdio_io_port_5_mdc]
set_property PACKAGE_PIN B19 [get_ports rgmii_port_6_rxc]
set_property PACKAGE_PIN G15 [get_ports {rgmii_port_6_rd[2]}]
set_property PACKAGE_PIN G16 [get_ports {rgmii_port_6_rd[3]}]
set_property PACKAGE_PIN F18 [get_ports {rgmii_port_7_rd[0]}]
set_property PACKAGE_PIN E18 [get_ports {rgmii_port_7_rd[2]}]
set_property PACKAGE_PIN K19 [get_ports rgmii_port_4_rxc]
set_property PACKAGE_PIN K20 [get_ports rgmii_port_4_rx_ctl]
set_property PACKAGE_PIN J20 [get_ports {rgmii_port_4_rd[2]}]
set_property PACKAGE_PIN K21 [get_ports {rgmii_port_4_rd[3]}]
set_property PACKAGE_PIN J21 [get_ports {rgmii_port_4_td[1]}]
set_property PACKAGE_PIN J22 [get_ports {rgmii_port_4_td[2]}]
set_property PACKAGE_PIN P22 [get_ports {rgmii_port_5_td[0]}]
set_property PACKAGE_PIN N15 [get_ports {rgmii_port_5_td[2]}]
set_property PACKAGE_PIN P15 [get_ports {rgmii_port_5_td[3]}]
set_property PACKAGE_PIN G20 [get_ports rgmii_port_6_rx_ctl]
set_property PACKAGE_PIN G21 [get_ports {rgmii_port_6_rd[0]}]
set_property PACKAGE_PIN G17 [get_ports {rgmii_port_6_td[1]}]
set_property PACKAGE_PIN F17 [get_ports {rgmii_port_6_td[2]}]
set_property PACKAGE_PIN C15 [get_ports rgmii_port_6_tx_ctl]
set_property PACKAGE_PIN B15 [get_ports mdio_io_port_6_io]
set_property PACKAGE_PIN B17 [get_ports {rgmii_port_7_td[0]}]
set_property PACKAGE_PIN A16 [get_ports {rgmii_port_7_td[2]}]
set_property PACKAGE_PIN A17 [get_ports {rgmii_port_7_td[3]}]
set_property PACKAGE_PIN L18 [get_ports ref_clk_1_p]
set_property PACKAGE_PIN L19 [get_ports ref_clk_1_n]
set_property PACKAGE_PIN L21 [get_ports {rgmii_port_4_rd[0]}]
set_property PACKAGE_PIN L22 [get_ports {rgmii_port_4_rd[1]}]
set_property PACKAGE_PIN M21 [get_ports {rgmii_port_4_td[0]}]
set_property PACKAGE_PIN M22 [get_ports rgmii_port_4_txc]
set_property PACKAGE_PIN J15 [get_ports {rgmii_port_4_td[3]}]
set_property PACKAGE_PIN K15 [get_ports rgmii_port_4_tx_ctl]
set_property PACKAGE_PIN R20 [get_ports {rgmii_port_5_td[1]}]
set_property PACKAGE_PIN R21 [get_ports rgmii_port_5_txc]
set_property PACKAGE_PIN P20 [get_ports rgmii_port_5_tx_ctl]
set_property PACKAGE_PIN P21 [get_ports reset_port_5]
set_property PACKAGE_PIN E19 [get_ports {rgmii_port_6_rd[1]}]
set_property PACKAGE_PIN E20 [get_ports {rgmii_port_6_td[0]}]
set_property PACKAGE_PIN F21 [get_ports rgmii_port_6_txc]
set_property PACKAGE_PIN F22 [get_ports {rgmii_port_6_td[3]}]
set_property PACKAGE_PIN A21 [get_ports mdio_io_port_6_mdc]
set_property PACKAGE_PIN A22 [get_ports reset_port_6]
set_property PACKAGE_PIN D22 [get_ports {rgmii_port_7_td[1]}]
set_property PACKAGE_PIN C22 [get_ports rgmii_port_7_txc]
set_property PACKAGE_PIN E21 [get_ports rgmii_port_7_tx_ctl]
set_property PACKAGE_PIN D21 [get_ports mdio_io_port_7_mdc]
set_property PACKAGE_PIN B21 [get_ports mdio_io_port_7_io]
set_property PACKAGE_PIN B22 [get_ports reset_port_7]

create_clock -period 8.000 -name ref_clk_1_p -waveform {0.000 4.000} [get_ports ref_clk_1_p]

# The following constraints are here to override some of the automatically
# generated constraints for the AXI Ethernet IPs. Specifically the
# grouping of the IDELAY_CTRLs and the IDELAYs.

current_instance design_1_i/axi_ethernet_0/U0/eth_mac/U0
set_property IODELAY_GROUP tri_mode_ethernet_mac_iodelay_grp0 [get_cells {tri_mode_ethernet_mac_i/rgmii_interface/delay_rgmii_rx* tri_mode_ethernet_mac_i/rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
current_instance -quiet

current_instance design_1_i/axi_ethernet_1/U0/eth_mac/U0
set_property IODELAY_GROUP tri_mode_ethernet_mac_iodelay_grp0 [get_cells {rgmii_interface/delay_rgmii_rx* rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
current_instance -quiet

current_instance design_1_i/axi_ethernet_2/U0/eth_mac/U0
set_property IODELAY_GROUP tri_mode_ethernet_mac_iodelay_grp0 [get_cells {rgmii_interface/delay_rgmii_rx* rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
current_instance -quiet

current_instance design_1_i/axi_ethernet_3/U0/eth_mac/U0
set_property IODELAY_GROUP tri_mode_ethernet_mac_iodelay_grp0 [get_cells {rgmii_interface/delay_rgmii_rx* rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
current_instance -quiet

current_instance design_1_i/axi_ethernet_4/U0/eth_mac/U0
set_property IODELAY_GROUP tri_mode_ethernet_mac_iodelay_grp1 [get_cells {tri_mode_ethernet_mac_i/rgmii_interface/delay_rgmii_rx* tri_mode_ethernet_mac_i/rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
current_instance -quiet

current_instance design_1_i/axi_ethernet_5/U0/eth_mac/U0
set_property IODELAY_GROUP tri_mode_ethernet_mac_iodelay_grp1 [get_cells {rgmii_interface/delay_rgmii_rx* rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
current_instance -quiet

current_instance design_1_i/axi_ethernet_6/U0/eth_mac/U0
set_property IODELAY_GROUP tri_mode_ethernet_mac_iodelay_grp1 [get_cells {rgmii_interface/delay_rgmii_rx* rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
current_instance -quiet

current_instance design_1_i/axi_ethernet_7/U0/eth_mac/U0
set_property IODELAY_GROUP tri_mode_ethernet_mac_iodelay_grp1 [get_cells {rgmii_interface/delay_rgmii_rx* rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
current_instance -quiet

# Constraints for IDELAY_CTRL grouping
# The automatically generated constraints group the IDELAY_CTRLs into the
# same group, however in a design with 4 AXI Ethernet IPs, this is not
# possible to achieve because they will be spread across 2 banks.
# The following constraints group the IDELAY_CTRLs into two separate
# groups, one for each bank.

set_property IODELAY_GROUP tri_mode_ethernet_mac_iodelay_grp0 [get_cells design_1_i/axi_ethernet_0/U0/eth_mac/U0/tri_mode_ethernet_mac_idelayctrl_common_i]
set_property IODELAY_GROUP tri_mode_ethernet_mac_iodelay_grp1 [get_cells design_1_i/axi_ethernet_4/U0/eth_mac/U0/tri_mode_ethernet_mac_idelayctrl_common_i]
