################################################################
# These are the constraints for the ZC706 evaluation board with
# two Ethernet FMCs - one connected to each FMC connector
################################################################

# WARNING: These constraints are provided for reference only. The ZC706 HPC pins
# LA17_CC and LA18_CC are routed to non-clock-capable pins and thus cannot properly
# receive the RGMII receive clock for ports 2 and 3 of the Ethernet FMC.
# These constraints as they are will not pass the Xilinx tools.

# Constraints for first Ethernet FMC plugged onto the LPC connector
# Ports are numbered 0 to 3

# Enable internal termination resistor on LVDS 125MHz ref_clk
set_property DIFF_TERM TRUE [get_ports ref_clk_0_p]
set_property DIFF_TERM TRUE [get_ports ref_clk_0_n]

# Define I/O standards
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_1_rd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_0_mdio_io]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_1_rd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ref_clk_0_fsel[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_1_mdio_io]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_3_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_3_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_3_rd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_3_rd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_1_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_1_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_0_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports reset_port_0]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_1_rd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_1_rd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ref_clk_0_oe[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_1_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_2_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_2_rd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_2_rd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_3_rd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_3_rd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_0_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_0_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_0_rd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_0_rd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_0_td[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_0_td[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_1_td[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_1_td[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_1_td[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_2_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_2_rd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_2_td[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_2_td[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_2_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_2_mdio_io]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_3_td[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_3_td[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_3_td[3]}]
set_property IOSTANDARD LVDS_25 [get_ports ref_clk_0_p]
set_property IOSTANDARD LVDS_25 [get_ports ref_clk_0_n]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_0_rd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_0_rd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_0_td[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_0_txc]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_0_td[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_0_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_1_td[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_1_txc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_1_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports reset_port_1]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_2_rd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_2_td[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_2_txc]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_2_td[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_2_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports reset_port_2]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_3_td[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_3_txc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_3_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_3_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_3_mdio_io]
set_property IOSTANDARD LVCMOS25 [get_ports reset_port_3]

set_property PACKAGE_PIN AB12 [get_ports {rgmii_port_1_rd[0]}]
set_property PACKAGE_PIN AC12 [get_ports mdio_io_port_0_mdio_io]
set_property PACKAGE_PIN AC13 [get_ports {rgmii_port_1_rd[2]}]
set_property PACKAGE_PIN AF18 [get_ports {ref_clk_0_fsel[0]}]
set_property PACKAGE_PIN AF17 [get_ports mdio_io_port_1_mdio_io]
set_property PACKAGE_PIN AE27 [get_ports rgmii_port_3_rxc]
set_property PACKAGE_PIN AF27 [get_ports rgmii_port_3_rx_ctl]
set_property PACKAGE_PIN AJ28 [get_ports {rgmii_port_3_rd[1]}]
set_property PACKAGE_PIN AJ29 [get_ports {rgmii_port_3_rd[3]}]
set_property PACKAGE_PIN AF15 [get_ports rgmii_port_1_rxc]
set_property PACKAGE_PIN AG15 [get_ports rgmii_port_1_rx_ctl]
set_property PACKAGE_PIN AE16 [get_ports mdio_io_port_0_mdc]
set_property PACKAGE_PIN AE15 [get_ports reset_port_0]
set_property PACKAGE_PIN AH14 [get_ports {rgmii_port_1_rd[1]}]
set_property PACKAGE_PIN AH13 [get_ports {rgmii_port_1_rd[3]}]
set_property PACKAGE_PIN AH17 [get_ports {ref_clk_0_oe[0]}]
set_property PACKAGE_PIN AH16 [get_ports mdio_io_port_1_mdc]
set_property PACKAGE_PIN AB27 [get_ports rgmii_port_2_rxc]
set_property PACKAGE_PIN AJ26 [get_ports {rgmii_port_2_rd[2]}]
set_property PACKAGE_PIN AK26 [get_ports {rgmii_port_2_rd[3]}]
set_property PACKAGE_PIN AJ30 [get_ports {rgmii_port_3_rd[0]}]
set_property PACKAGE_PIN AK30 [get_ports {rgmii_port_3_rd[2]}]
set_property PACKAGE_PIN AE13 [get_ports rgmii_port_0_rxc]
set_property PACKAGE_PIN AF13 [get_ports rgmii_port_0_rx_ctl]
set_property PACKAGE_PIN AG12 [get_ports {rgmii_port_0_rd[2]}]
set_property PACKAGE_PIN AH12 [get_ports {rgmii_port_0_rd[3]}]
set_property PACKAGE_PIN AD14 [get_ports {rgmii_port_0_td[1]}]
set_property PACKAGE_PIN AD13 [get_ports {rgmii_port_0_td[2]}]
set_property PACKAGE_PIN AD15 [get_ports {rgmii_port_1_td[0]}]
set_property PACKAGE_PIN AE18 [get_ports {rgmii_port_1_td[2]}]
set_property PACKAGE_PIN AE17 [get_ports {rgmii_port_1_td[3]}]
set_property PACKAGE_PIN AG26 [get_ports rgmii_port_2_rx_ctl]
set_property PACKAGE_PIN AG27 [get_ports {rgmii_port_2_rd[0]}]
set_property PACKAGE_PIN AK27 [get_ports {rgmii_port_2_td[1]}]
set_property PACKAGE_PIN AK28 [get_ports {rgmii_port_2_td[2]}]
set_property PACKAGE_PIN AF29 [get_ports rgmii_port_2_tx_ctl]
set_property PACKAGE_PIN AG29 [get_ports mdio_io_port_2_mdio_io]
set_property PACKAGE_PIN AF25 [get_ports {rgmii_port_3_td[0]}]
set_property PACKAGE_PIN AC29 [get_ports {rgmii_port_3_td[2]}]
set_property PACKAGE_PIN AD29 [get_ports {rgmii_port_3_td[3]}]
set_property PACKAGE_PIN AG17 [get_ports ref_clk_0_p]
set_property PACKAGE_PIN AG16 [get_ports ref_clk_0_n]
set_property PACKAGE_PIN AE12 [get_ports {rgmii_port_0_rd[0]}]
set_property PACKAGE_PIN AF12 [get_ports {rgmii_port_0_rd[1]}]
set_property PACKAGE_PIN AJ15 [get_ports {rgmii_port_0_td[0]}]
set_property PACKAGE_PIN AK15 [get_ports rgmii_port_0_txc]
set_property PACKAGE_PIN AA15 [get_ports {rgmii_port_0_td[3]}]
set_property PACKAGE_PIN AA14 [get_ports rgmii_port_0_tx_ctl]
set_property PACKAGE_PIN AJ16 [get_ports {rgmii_port_1_td[1]}]
set_property PACKAGE_PIN AK16 [get_ports rgmii_port_1_txc]
set_property PACKAGE_PIN AB15 [get_ports rgmii_port_1_tx_ctl]
set_property PACKAGE_PIN AB14 [get_ports reset_port_1]
set_property PACKAGE_PIN AH26 [get_ports {rgmii_port_2_rd[1]}]
set_property PACKAGE_PIN AH27 [get_ports {rgmii_port_2_td[0]}]
set_property PACKAGE_PIN AH28 [get_ports rgmii_port_2_txc]
set_property PACKAGE_PIN AH29 [get_ports {rgmii_port_2_td[3]}]
set_property PACKAGE_PIN AF30 [get_ports mdio_io_port_2_mdc]
set_property PACKAGE_PIN AG30 [get_ports reset_port_2]
set_property PACKAGE_PIN AD25 [get_ports {rgmii_port_3_td[1]}]
set_property PACKAGE_PIN AE26 [get_ports rgmii_port_3_txc]
set_property PACKAGE_PIN AB29 [get_ports rgmii_port_3_tx_ctl]
set_property PACKAGE_PIN AB30 [get_ports mdio_io_port_3_mdc]
set_property PACKAGE_PIN Y26 [get_ports mdio_io_port_3_mdio_io]
set_property PACKAGE_PIN Y27 [get_ports reset_port_3]

create_clock -period 8.000 -name ref_clk_0_p -waveform {0.000 4.000} [get_ports ref_clk_0_p]

# Constraints for second Ethernet FMC plugged onto the HPC connector
# Ports are numbered 4 to 7

# Enable internal termination resistor on LVDS 125MHz ref_clk
set_property DIFF_TERM TRUE [get_ports ref_clk_1_p]
set_property DIFF_TERM TRUE [get_ports ref_clk_1_n]

# Define I/O standards
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_5_rd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_4_mdio_io]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_5_rd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ref_clk_1_fsel[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_5_mdio_io]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_7_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_7_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_7_rd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_7_rd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_5_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_5_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_4_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports reset_port_4]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_5_rd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_5_rd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ref_clk_1_oe[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_5_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_6_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_6_rd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_6_rd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_7_rd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_7_rd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_4_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_4_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_4_rd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_4_rd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_4_td[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_4_td[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_5_td[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_5_td[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_5_td[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_6_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_6_rd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_6_td[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_6_td[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_6_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_6_mdio_io]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_7_td[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_7_td[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_7_td[3]}]
set_property IOSTANDARD LVDS_25 [get_ports ref_clk_1_p]
set_property IOSTANDARD LVDS_25 [get_ports ref_clk_1_n]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_4_rd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_4_rd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_4_td[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_4_txc]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_4_td[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_4_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_5_td[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_5_txc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_5_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports reset_port_5]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_6_rd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_6_td[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_6_txc]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_6_td[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_6_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports reset_port_6]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_port_7_td[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_7_txc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_port_7_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_7_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_io_port_7_mdio_io]
set_property IOSTANDARD LVCMOS25 [get_ports reset_port_7]

set_property PACKAGE_PIN AG22 [get_ports {rgmii_port_5_rd[0]}]
set_property PACKAGE_PIN AH22 [get_ports mdio_io_port_4_mdio_io]
set_property PACKAGE_PIN AG25 [get_ports {rgmii_port_5_rd[2]}]
set_property PACKAGE_PIN AC24 [get_ports {ref_clk_1_fsel[0]}]
set_property PACKAGE_PIN AD24 [get_ports mdio_io_port_5_mdio_io]
set_property PACKAGE_PIN W25 [get_ports rgmii_port_7_rxc]
set_property PACKAGE_PIN W26 [get_ports rgmii_port_7_rx_ctl]
set_property PACKAGE_PIN V28 [get_ports {rgmii_port_7_rd[1]}]
set_property PACKAGE_PIN V29 [get_ports {rgmii_port_7_rd[3]}]
set_property PACKAGE_PIN AG21 [get_ports rgmii_port_5_rxc]
set_property PACKAGE_PIN AH21 [get_ports rgmii_port_5_rx_ctl]
set_property PACKAGE_PIN AH23 [get_ports mdio_io_port_4_mdc]
set_property PACKAGE_PIN AH24 [get_ports reset_port_4]
set_property PACKAGE_PIN AD21 [get_ports {rgmii_port_5_rd[1]}]
set_property PACKAGE_PIN AE21 [get_ports {rgmii_port_5_rd[3]}]
set_property PACKAGE_PIN AA22 [get_ports {ref_clk_1_oe[0]}]
set_property PACKAGE_PIN AA23 [get_ports mdio_io_port_5_mdc]
set_property PACKAGE_PIN V23 [get_ports rgmii_port_6_rxc]
set_property PACKAGE_PIN P25 [get_ports {rgmii_port_6_rd[2]}]
set_property PACKAGE_PIN P26 [get_ports {rgmii_port_6_rd[3]}]
set_property PACKAGE_PIN R28 [get_ports {rgmii_port_7_rd[0]}]
set_property PACKAGE_PIN T28 [get_ports {rgmii_port_7_rd[2]}]
set_property PACKAGE_PIN AF20 [get_ports rgmii_port_4_rxc]
set_property PACKAGE_PIN AG20 [get_ports rgmii_port_4_rx_ctl]
set_property PACKAGE_PIN AH19 [get_ports {rgmii_port_4_rd[2]}]
set_property PACKAGE_PIN AJ19 [get_ports {rgmii_port_4_rd[3]}]
set_property PACKAGE_PIN AF19 [get_ports {rgmii_port_4_td[1]}]
set_property PACKAGE_PIN AG19 [get_ports {rgmii_port_4_td[2]}]
set_property PACKAGE_PIN AF24 [get_ports {rgmii_port_5_td[0]}]
set_property PACKAGE_PIN AA24 [get_ports {rgmii_port_5_td[2]}]
set_property PACKAGE_PIN AB24 [get_ports {rgmii_port_5_td[3]}]
set_property PACKAGE_PIN U25 [get_ports rgmii_port_6_rx_ctl]
set_property PACKAGE_PIN V26 [get_ports {rgmii_port_6_rd[0]}]
set_property PACKAGE_PIN V27 [get_ports {rgmii_port_6_td[1]}]
set_property PACKAGE_PIN W28 [get_ports {rgmii_port_6_td[2]}]
set_property PACKAGE_PIN T29 [get_ports rgmii_port_6_tx_ctl]
set_property PACKAGE_PIN U29 [get_ports mdio_io_port_6_mdio_io]
set_property PACKAGE_PIN R26 [get_ports {rgmii_port_7_td[0]}]
set_property PACKAGE_PIN N29 [get_ports {rgmii_port_7_td[2]}]
set_property PACKAGE_PIN P29 [get_ports {rgmii_port_7_td[3]}]
set_property PACKAGE_PIN AE22 [get_ports ref_clk_1_p]
set_property PACKAGE_PIN AF22 [get_ports ref_clk_1_n]
set_property PACKAGE_PIN AK17 [get_ports {rgmii_port_4_rd[0]}]
set_property PACKAGE_PIN AK18 [get_ports {rgmii_port_4_rd[1]}]
set_property PACKAGE_PIN AJ20 [get_ports {rgmii_port_4_td[0]}]
set_property PACKAGE_PIN AK20 [get_ports rgmii_port_4_txc]
set_property PACKAGE_PIN AJ23 [get_ports {rgmii_port_4_td[3]}]
set_property PACKAGE_PIN AJ24 [get_ports rgmii_port_4_tx_ctl]
set_property PACKAGE_PIN AD23 [get_ports {rgmii_port_5_td[1]}]
set_property PACKAGE_PIN AE23 [get_ports rgmii_port_5_txc]
set_property PACKAGE_PIN Y22 [get_ports rgmii_port_5_tx_ctl]
set_property PACKAGE_PIN Y23 [get_ports reset_port_5]
set_property PACKAGE_PIN T24 [get_ports {rgmii_port_6_rd[1]}]
set_property PACKAGE_PIN T25 [get_ports {rgmii_port_6_td[0]}]
set_property PACKAGE_PIN W29 [get_ports rgmii_port_6_txc]
set_property PACKAGE_PIN W30 [get_ports {rgmii_port_6_td[3]}]
set_property PACKAGE_PIN T30 [get_ports mdio_io_port_6_mdc]
set_property PACKAGE_PIN U30 [get_ports reset_port_6]
set_property PACKAGE_PIN P30 [get_ports {rgmii_port_7_td[1]}]
set_property PACKAGE_PIN R30 [get_ports rgmii_port_7_txc]
set_property PACKAGE_PIN P23 [get_ports rgmii_port_7_tx_ctl]
set_property PACKAGE_PIN P24 [get_ports mdio_io_port_7_mdc]
set_property PACKAGE_PIN P21 [get_ports mdio_io_port_7_mdio_io]
set_property PACKAGE_PIN R21 [get_ports reset_port_7]

create_clock -period 8.000 -name ref_clk_1_p -waveform {0.000 4.000} [get_ports ref_clk_1_p]

