SET vivado=C:\Xilinx\Vivado\2015.2\bin\vivado.bat
start /wait cmd /c "%vivado% -mode batch -source build-ac701.tcl"
start /wait cmd /c "%vivado% -mode batch -source build-kc705-hpc.tcl"
start /wait cmd /c "%vivado% -mode batch -source build-kc705-lpc.tcl"
start /wait cmd /c "%vivado% -mode batch -source build-kc705-lpc-hpc.tcl"
start /wait cmd /c "%vivado% -mode batch -source build-vc707-hpc1.tcl"
start /wait cmd /c "%vivado% -mode batch -source build-vc707-hpc2.tcl"
start /wait cmd /c "%vivado% -mode batch -source build-vc707-hpc2-hpc1.tcl"
start /wait cmd /c "%vivado% -mode batch -source build-vc709.tcl"
start /wait cmd /c "%vivado% -mode batch -source build-zc702-lpc1.tcl"
start /wait cmd /c "%vivado% -mode batch -source build-zc702-lpc2.tcl"
start /wait cmd /c "%vivado% -mode batch -source build-zc702-lpc2-lpc1.tcl"
start /wait cmd /c "%vivado% -mode batch -source build-zc706-lpc.tcl"
